version: '3'

services:
  api:
    build:
      context: ./dockerfiles/api
      dockerfile: Dockerfile
    image: neverscapealone-api:latest
    ports:
      - "5500:5500"
    env_file:
      - .env
    volumes:
      - /home/ubuntu/nsa/match_histories:/prod/histories:rw
      - /home/ubuntu/nsa/errors:/prod/errors:rw
      - /home/ubuntu/nsa/errors:/prod/logs:rw
  dev:
    build:
      context: ./dockerfiles/dev
      dockerfile: Dockerfile
    image: neverscapealone-api-dev:latest
    ports:
      - "5501:5501"
    env_file:
      - .env
    volumes:
      - /home/ubuntu/nsa_dev/match_histories:/dev/histories:rw
      - /home/ubuntu/nsa_dev/errors:/dev/errors:rw
      - /home/ubuntu/nsa_dev/errors:/dev/logs:rw
