version: '3'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: neverscapealone-api:latest
    ports:
      - "5500:5500"
    env_file:
      - .env
    volumes:
      - /home/ubuntu/nsa/match_histories:/code/histories:rw
      - /home/ubuntu/nsa/errors:/code/errors:rw
      - /home/ubuntu/nsa/errors:/code/logs:rw
