name: Deployment workflow
on:
  push:
    branches: [ main ]

jobs:
  checkout:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: Set Up ENV
      run: |
          echo "${{ secrets.SQL_URI }}" > .env
          echo "${{ secrets.DISCORD_ROUTE_TOKEN}}" >> .env
          echo "${{ secrets.REDIS_PASSWORD}}" >> .env
  deploy:
    runs-on: self-hosted
    needs: [checkout]
    steps:
      - name: Docker
        run: |
          sudo docker-compose up --build -d